### ISSUE TITLE
Connecting a solar panel?

### ISSUE THREAD

**Issue by Humancell** [Xinyuan-LilyGO/T-Energy-S3#1]
Hello,

Does this board support connecting a solar panel directly for charging?  If so, which pins should be used for this, and what specs for the solar panel are recommended?

This is an awesome board!

**Comment by Llgok** [comment]
@Humancell 
The T-Energy-S3 does not feature a dedicated charging port for solar panels. Instead, you can charge it using USB power. Furthermore, most solar panels available on the market can be utilized for this purpose. However, you will need to construct a voltage stabilization module on your own to provide a stable 5V output for charging the T-Energy-S3.
