### ISSUE TITLE
How to open i2c sensor through qwiic?

### ISSUE THREAD

**Issue by chwan1** [Xinyuan-LilyGO/T-Energy-S3#3]
I'd like to evaluate [Adafruit_BNO08x](https://github.com/adafruit/Adafruit_BNO08x) from qwiic connector. But cannot open the sensor.
I was using [this code](https://github.com/adafruit/Adafruit_BNO08x/blob/master/examples/rotation_vector/rotation_vector.ino) and I added `Wire.setPins(37, 36);` before line 23. Is pin 37 and 36 the correct pin for i2c?

**Comment by Llgok** [comment]
@chwan1 
Does your I2C circuit have pull-up resistors?

**Comment by chwan1** [comment]
According to the [schematic](https://learn.adafruit.com/assets/94834) I think it has pull-up risistors built-in.

**Comment by Llgok** [comment]
@chwan1 
T-Energy_V1.0 utilizes the ESP32S3R8 main chip. The ESP32S3R8 integrates the IO35, IO36, and IO37 chips internally, which cannot be repurposed for other functions. You can use other pins for IIC operations.

**Comment by chwan1** [comment]
Can I clearify that the qwiic connector in T-Energy cannot be used as I2C connection?

**Comment by Llgok** [comment]
@chwan1 

The external IO ports on T-Energy, except for IO35, IO36, and IO37, can all be remapped as hardware IIC. Is the qwiic interface you mentioned referring to the uart interface on the board? It can also be remapped as IIC, but it requires external pull-up, and the pins are IO43 and IO44.You can refer to the example program [IIC\_Scan\_2](https://github.com/Xinyuan-LilyGO/T-Energy-S3/tree/main/examples/IIC_Scan_2) to debug the IIC.

T-Energy上的外置IO口除了IO35、IO36、IO37之外，其他IO口i都可以重映射為硬體IIC。您所說的qwiic接口是指板子上的uart接口嗎？它也可以重映射為IIC，但是需要外部上拉，引腳為IO43、IO44。您可以參考示例程式 [IIC\_Scan\_2](https://github.com/Xinyuan-LilyGO/T-Energy-S3/tree/main/examples/IIC_Scan_2) 來調試 IIC

**Comment by Llgok** [comment]
@chwan1 
![1](https://github.com/user-attachments/assets/443a004f-d7d7-47e8-ba3d-cb20d4f85ec5)

**Comment by chwan1** [comment]
Thanks for the help! It worked with pin 43 and 44.

The qwiic connector is refered in your [webpage](https://www.lilygo.cc/products/t-energy-s3). 
![image](https://github.com/user-attachments/assets/28e7ca09-a742-4445-a1e8-791aa6fe0ad6)

May I suggest that the pin info of qwiic/uart to be put into the schema file?

**Comment by Llgok** [comment]
@chwan1 
Alright, I will add the UART pin information to the README.md file later.
