### ISSUE TITLE
LED2 The blue LED that stays on all the time is on the wrong side of the protection circuitry 

### ISSUE THREAD

**Issue by aschwartzmann** [Xinyuan-LilyGO/T-Energy-S3#4]
### IDE and version or firmware

All

### Operating System

All

### Description

LED2, The blue LED that stays on all the time is connected directly to the battery via a resistor. It's on the wrong side of the protection circuitry. So it will continue to drain the battery after the protection circuit kicks in to protect the battery. The schematic  T-Energy-S3_V1.0.pdf in this repository shows PY2 in the bottom left of the drawing. That is the battery holder. The IP3005 IC is the IC to protect the battery from over-discharge. If the LED was connected between BAT+ and GND then it would turn off when the protection kicks in but it's connected between VBAT+ and VBAT-. Also, an even better place to put it would be between VCC5V and GND that way it would turn off with the switch.

### Sketch

```cpp
N/A
```

### Debug Message

```plain
N/A
```

### Other steps to Reproduce

N/A

**Comment by Llgok** [comment]
@aschwartzmann 
The blue LED serves as a polarity warning indicator. It is used to alert you if the 18650 battery is inserted with the polarity reversed. If the 18650 battery is correctly connected with the positive and negative poles aligned, the LED should not light up and should not consume battery power continuously.

**Comment by Llgok** [comment]
Closed due to prolonged lack of response
